spring.application.name=lpgen
server.port=${PORT:8080}
spring.data.mongodb.uri=${SPRING_MONGO_URI}
spring.data.mongodb.database=LPGENDB
groq.api.key=${GROQ_API_KEY}
youtube.api.key=${YOUTUBE_API_KEY}
serp.api.key=${SERP_API_KEY}
management.endpoints.web.exposure.include=health
