spring.application.name=lpgen
spring.data.mongodb.uri=mongodb+srv://sakshimaske7148_db_user:MFvM3UKLcoORaeFC@clusterlpgen.sfrwgs0.mongodb.net/?retryWrites=true&w=majority&readPreference=primary&appName=ClusterLPGEN
spring.data.mongodb.database=LPGENDB
openai.api.key=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