spring.application.name=lpgen
spring.data.mongodb.uri=${SPRING_MONGO_URI}
spring.data.mongodb.database=LPGENDB
groq.api.key=${GROQ_API_KEY}
youtube.api.key=${YOUTUBE_API_KEY}
serp.api.key=${SERP_API_KEY}
